version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/backend/data/postgres
    ports:
      - "5431:5432"
    networks: 
      - production-network


  api:
    container_name: api
    build: 
      context: src
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_NAME: ${POSTGRES_NAME}
    ports:
        - 3333:3333
    command: python3 main.py
    depends_on:
        - "postgres"
    networks: 
      - production-network

volumes:
    postgres:

networks:
  production-network:
    driver: bridge